import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Header Section */}
        <header className="bg-gray-100 shadow">
          {/* Full-Width Background */}
          <div className="w-full bg-gray-200">
            {/* Centered Header Container */}
            <div className="mx-auto max-w-[1200px] px-4 pt-3">
              {/* Top bar */}
              <div className="flex items-center justify-between">
                {/* Left Section */}
                <div className="text-lg font-bold text-gray-700">Real Estate</div>

                {/* Right Login Button */}
                <div>
                  <Link
                    href="/login"
                    className="px-4 py-2 text-sm font-medium text-white bg-blue-500 rounded hover:bg-blue-600"
                  >
                    Login
                  </Link>
                </div>
              </div>
              <div className="flex overflow-x-auto space-x-4 p-4">

  <div className="flex-shrink-0 w-24 p-1 border rounded-lg flex flex-col items-center">

    <div className="mb-2">
      <svg className="w-6 h-6 text-gray-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v14m7-7H5"></path>
      </svg>
    </div>
   
    <div className="text-center text-sm font-semibold text-gray-700">
      Шинэ орон сууц
    </div>
  </div>


  <div className="flex-shrink-0 w-24 p-1 border rounded-lg flex flex-col items-center">
    <div className="mb-2">
      <svg className="w-6 h-6 text-gray-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v14m7-7H5"></path>
      </svg>
    </div>
    <div className="text-center text-sm font-semibold text-gray-700">
      Item 2
    </div>
  </div>

  
  <div className="flex-shrink-0 w-24 p-1 border rounded-lg flex flex-col items-center">
    <div className="mb-2">
      <svg className="w-6 h-6 text-gray-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v14m7-7H5"></path>
      </svg>
    </div>
    <div className="text-center text-sm font-semibold text-gray-700">
      Item 3
    </div>
  </div>
   
  <div className="flex-shrink-0 w-24 p-1 border rounded-lg flex flex-col items-center">
    <div className="mb-2">
      <svg className="w-6 h-6 text-gray-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v14m7-7H5"></path>
      </svg>
    </div>
    <div className="text-center text-sm font-semibold text-gray-700">
      Item 3
    </div>
  </div>
   
  <div className="flex-shrink-0 w-24 p-1 border rounded-lg flex flex-col items-center">
    <div className="mb-2">
      <svg className="w-6 h-6 text-gray-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v14m7-7H5"></path>
      </svg>
    </div>
    <div className="text-center text-sm font-semibold text-gray-700">
      Item 3
    </div>
  </div>
   
  <div className="flex-shrink-0 w-24 p-1 border rounded-lg flex flex-col items-center">
    <div className="mb-2">
      <svg className="w-6 h-6 text-gray-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v14m7-7H5"></path>
      </svg>
    </div>
    <div className="text-center text-sm font-semibold text-gray-700">
      Item 3
    </div>
  </div>
   
  <div className="flex-shrink-0 w-24 p-1 border rounded-lg flex flex-col items-center">
    <div className="mb-2">
      <svg className="w-6 h-6 text-gray-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v14m7-7H5"></path>
      </svg>
    </div>
    <div className="text-center text-sm font-semibold text-gray-700">
      Item 3
    </div>
  </div>

   
  <div className="flex-shrink-0 w-24 p-1 border rounded-lg flex flex-col items-center">
    <div className="mb-2">
      <svg className="w-6 h-6 text-gray-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v14m7-7H5"></path>
      </svg>
    </div>
    <div className="text-center text-sm font-semibold text-gray-700">
      Item 3
    </div>
  </div>
   
  <div className="flex-shrink-0 w-24 p-1 border rounded-lg flex flex-col items-center">
    <div className="mb-2">
      <svg className="w-6 h-6 text-gray-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v14m7-7H5"></path>
      </svg>
    </div>
    <div className="text-center text-sm font-semibold text-gray-700">
      Item 3
    </div>
  </div>
   
  <div className="flex-shrink-0 w-24 p-1 border rounded-lg flex flex-col items-center">
    <div className="mb-2">
      <svg className="w-6 h-6 text-gray-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v14m7-7H5"></path>
      </svg>
    </div>
    <div className="text-center text-sm font-semibold text-gray-700">
      Item 3
    </div>
  </div>
   
  <div className="flex-shrink-0 w-24 p-1 border rounded-lg flex flex-col items-center">
    <div className="mb-2">
      <svg className="w-6 h-6 text-gray-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v14m7-7H5"></path>
      </svg>
    </div>
    <div className="text-center text-sm font-semibold text-gray-700">
      Item 3
    </div>
  </div>
   
  <div className="flex-shrink-0 w-24 p-1 border rounded-lg flex flex-col items-center">
    <div className="mb-2">
      <svg className="w-6 h-6 text-gray-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v14m7-7H5"></path>
      </svg>
    </div>
    <div className="text-center text-sm font-semibold text-gray-700">
      Item 3
    </div>
  </div>
   
  <div className="flex-shrink-0 w-24 p-1 border rounded-lg flex flex-col items-center">
    <div className="mb-2">
      <svg className="w-6 h-6 text-gray-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v14m7-7H5"></path>
      </svg>
    </div>
    <div className="text-center text-sm font-semibold text-gray-700">
      Item 3
    </div>
  </div>
  


</div>

              {/* Navigation Menu */}
              <nav className="menu mt-4">
                <ul className="menu-list flex space-x-6">
                  <li>
                    <Link href="/" className="menu-link text-gray-700 hover:text-blue-500">
                      Шинэ орон сууц
                    </Link>
                  </li>
                  <li>
                    <Link href="/about/index.tsx" className="menu-link text-gray-700 hover:text-blue-500">
                      Орон сууц
                    </Link>
                  </li>
                  <li>
                    <Link href="/about" className="menu-link text-gray-700 hover:text-blue-500">
                      Хашаа байшин
                    </Link>
                  </li>
                  <li>
                    <Link href="/about/" className="menu-link text-gray-700 hover:text-blue-500">
                      Газар
                    </Link>
                  </li>
                  <li>
                    <Link href="/about" className="menu-link text-gray-700 hover:text-blue-500">
                      Үл хөдлөх
                    </Link>
                  </li>
                  <li>
                    <Link href="/contact" className="menu-link text-gray-700 hover:text-blue-500">
                      Автомашин
                    </Link>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
        </header>

        {/* Main Body */}
        <main className="mx-auto max-w-[1200px] px-4">{children}</main>
      </body>
    </html>
  );
}
